import type { StorePickupSlot } from "./StorePickupSlot";

/**
 * IStorePickupSlotRepository — domain port.
 *
 * Concrete implementation: PrismaPickupSlotRepository
 *
 * The repository never enforces the no-overlap rule — that belongs in the
 * application layer (CreatePickupSlotUseCase).  The repo only performs I/O.
 */
export interface IStorePickupSlotRepository {
  // ─── Queries ──────────────────────────────────────────────────────────────

  /**
   * All slots for a store, optionally scoped to a single dayOfWeek.
   * Ordered by dayOfWeek ASC, startTime ASC.
   */
  findByStore(
    storeId: string,
    opts?: { dayOfWeek?: number; activeOnly?: boolean },
  ): Promise<StorePickupSlot[]>;

  /**
   * Find a single slot by id, scoped by storeId (multi-tenant safety).
   * Returns null if not found or belongs to a different store.
   */
  findById(id: string, storeId: string): Promise<StorePickupSlot | null>;

  // ─── Mutations ─────────────────────────────────────────────────────────────

  /** Persist a new slot. id is generated by the DB. */
  create(
    storeId: string,
    dayOfWeek: number,
    startTime: string,
    endTime: string,
  ): Promise<StorePickupSlot>;

  /**
   * Flip isActive on an existing slot.
   * Returns null if the slot does not exist or belongs to a different store.
   */
  setActive(
    id: string,
    storeId: string,
    isActive: boolean,
  ): Promise<StorePickupSlot | null>;
}
